#pragma config(Sensor, in1,    BouncyRight,    sensorLineFollower)
#pragma config(Sensor, in2,    BouncyMid,      sensorLineFollower)
#pragma config(Sensor, in3,    BouncyLeft,     sensorLineFollower)
#pragma config(Sensor, in4,    Pot,            sensorPotentiometer)
#pragma config(Sensor, in5,    Light1,         sensorReflection)
#pragma config(Sensor, dgtl2,  SonarIn,        sensorSONAR_mm)
#pragma config(Sensor, dgtl4,  Limit,          sensorTouch)
#pragma config(Sensor, dgtl5,  Button,         sensorTouch)
#pragma config(Sensor, dgtl6,  LEDR,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl7,  LEDY,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl8,  LEDG,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl9,  EncodRa,        sensorQuadEncoder)
#pragma config(Sensor, dgtl11, EncodLa,        sensorQuadEncoder)
#pragma config(Motor,  port1,           Flashy,        tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           TankRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           TankLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Servo,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: TWR_2a
  Team Members: Josh L && Zak S
  Date: 3/6/20
  Summary: If Else


  Task Description: Use an If Else statement to write a program so that the green Led will turn on and stay on when the button is
pushed. Then if the potentiometer is less than 2500 the yellow LED will be on and if the potentiometer is
greater than or equal to 2500 the red LED will be on. This program should run infinitely.



  Pseudocode:
		Do forever:
			If the button is pushed:
				Turn the green LED on
			Otherwise:
				Turn the green LED off

			If the Pot is less than 2500:
				Turn the yellow LED on
				Turn the red LED off
			Otherwise:
				Turn the yellow LED off
				Turn the red LED on
*/
task main()
{                                     //Program begins, insert code within curly braces
	while(true){
	if(SensorValue[Button]==1)
	{
		turnLEDOn(LEDG);
	} else {
		turnLEDOff(LEDG);
	}

	if(SensorValue[Pot]<2500)
	{
		turnLEDOn(LEDY);
		turnLEDOff(LEDR);
	} else {
		turnLEDOn(LEDR);
		turnLEDOff(LEDY);
	}
	}
}
