#pragma config(Sensor, in1,    BouncyRight,    sensorLineFollower)
#pragma config(Sensor, in2,    BouncyMid,      sensorLineFollower)
#pragma config(Sensor, in3,    BouncyLeft,     sensorLineFollower)
#pragma config(Sensor, in4,    Pot,            sensorPotentiometer)
#pragma config(Sensor, in5,    Light1,         sensorReflection)
#pragma config(Sensor, dgtl2,  SonarIn,        sensorSONAR_mm)
#pragma config(Sensor, dgtl4,  Limit,          sensorTouch)
#pragma config(Sensor, dgtl5,  Button,         sensorTouch)
#pragma config(Sensor, dgtl6,  LEDR,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl7,  LEDY,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl8,  LEDG,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl9,  EncodRa,        sensorQuadEncoder)
#pragma config(Sensor, dgtl11, EncodLa,        sensorQuadEncoder)
#pragma config(Motor,  port1,           Flashy,        tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           TankRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           TankLeft,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           Servo,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: TWR_3
  Team Members: Josh L && Zak S
  Date: 3/11
  Summary: Ten Inches Away


  Task Description: Have the rover wait for the button to be pushed then turn on the green LED, drive forward unit 10
inches from the wall then turn off the green LED, stop, turn on the red LED for 2 seconds. The
rover will be placed different distance from the wall each time. Hint use the ultrasonic sensor.


  Pseudocode:
  	Notes:
  		- Threshold is 0.1"
  		- Drive Speed is determined by a fraction determined by the distance read over 30. If this fraction is greater than 3,
  		  speed is automatically 127. If it's less than one, the robot will back up a little.

		Wait for the button to pushed
		Turn on the Green LED (GO)
		While the robot is not ten inches away from the wall:
			Find the distance and set drive speed
			Drive Forward at drive speed

		Stop the motors
		Turn off Green LED.
		Turn on the Red LED.
		Wait 2 seconds.
		Turn off the Red LED.

*/
float drivedifference = 0;
void drive(float drivespeed)
{
	drivedifference = (-1*SensorValue[EncodLa]) + SensorValue[EncodRa];
  startMotor(TankLeft, drivespeed); //Drive forward
	startMotor(TankRight, drivespeed + drivedifference);//-44
}


task main()
{                                     //Program begins, insert code within curly braces
	untilTouch(Button);
	float distance = 100;
	float drivespeed = 20;
	bool done = false;
	turnLEDOn(LEDG);
	while(!done){
		distance = SensorValue[SonarIn]*0.0393701;
		if(distance < 30 && distance > 11.05){
			drivespeed = (distance/30)*127;
		}else if(distance > 9.85 && distance < 11.05){
			drivespeed = 0;
			done = true;
		}else if(distance < 9.85){
			drivespeed = -20;
 		}else{
 			drivespeed = 127;
 		}
 		drive(drivespeed);
	}
	stopMotor(TankLeft); // Stop
	stopMotor(TankRight);
	turnLEDOff(LEDG);
	turnLEDOn(LEDR);
	wait(2);
	turnLEDOff(LEDR);
}
