#pragma config(Sensor, in1,    BouncyRight,    sensorLineFollower)
#pragma config(Sensor, in2,    BouncyMid,      sensorLineFollower)
#pragma config(Sensor, in3,    BouncyLeft,     sensorLineFollower)
#pragma config(Sensor, in4,    Pot,            sensorPotentiometer)
#pragma config(Sensor, in5,    Light1,         sensorReflection)
#pragma config(Sensor, dgtl2,  SonarIn,        sensorSONAR_mm)
#pragma config(Sensor, dgtl4,  Limit,          sensorTouch)
#pragma config(Sensor, dgtl5,  Button,         sensorTouch)
#pragma config(Sensor, dgtl6,  LEDR,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl7,  LEDY,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl8,  LEDG,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl9,  EncodRa,        sensorQuadEncoder)
#pragma config(Sensor, dgtl11, EncodLa,        sensorQuadEncoder)
#pragma config(Motor,  port1,           Flashy,        tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           TankRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           TankLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Servo,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: TWR_1d
  Team Members: Josh L && Zak S
  Date: 2/24/20
  Summary: Obstacle Avoidance


  Task Description:
            Have the rover wait for the button to be pushed then turn on the flashlight and  travel from the start box to the end box while going around the X. The rover should stop and turn off the flashlight when properly in place in the end box.

  Pseudocode:
            Wait for button push then
            Turn on the flashlight
            Turn on the green LED
            Set drive motors to drive forward
            Wait 3 sec
            Set the green LED to 0
            Set drive motor left to driveSpeedL
            Set drive motor right to -1 * driveSpeedR
            Wait x seconds
            Set drive motor left to driveSpeedL
            Set drive motor right to driveSpeedR
            Wait x seconds
            Set drive motor left to driveSpeedL
            Set drive motor right to -1 * driveSpeedR
            Wait x seconds
            Set drive motors to drive forward
            Wait 3 sec
            Stop the drive motors
            Turn the flashlight off
            Turn red LED on
            Wait 1 sec
            Turn red LED off
*/

task main()
{                                     //Program begins, insert code within curly braces
	int driveMax = 100;
	//float turnTime = 0.97; //For 180*
	float turnTime90 = (0.55);
	int outdistance = 3;
	// int motorOffset = 0;
	int driveSpeedL = (driveMax+6);
	int driveSpeedR = (driveMax-18);
	int driveSpeedTurn = driveMax;
  while (true)
  {
    untilTouch(Button);
    turnLEDOn(LEDY);
    turnFlashlightOn(Flashy, driveMax);
    wait(1.5);

	  turnLEDOn(LEDG);
	  startMotor(TankRight, driveSpeedR);
    startMotor(TankLeft, driveSpeedL);
	  wait(outdistance);

	  startMotor(TankRight, -driveSpeedTurn);
    startMotor(TankLeft, driveSpeedTurn);
	  wait(turnTime90);

	  startMotor(TankRight, driveSpeedR);
    startMotor(TankLeft, driveSpeedL);
	  wait(outdistance - 0.8);

	  startMotor(TankRight, -driveSpeedTurn);
    startMotor(TankLeft, driveSpeedTurn);
	  wait(turnTime90);

	  startMotor(TankRight, driveSpeedR);
    startMotor(TankLeft, driveSpeedL);
	  wait(outdistance-0.5);

	  stopMotor(TankRight);
    stopMotor(TankLeft);

    turnLEDOff(LEDG);
    turnLEDOff(LEDY);
    turnFlashlightOff(Flashy);
    turnLEDOn(LEDR);
	  wait(1);
	  turnLEDOff(LEDR);

  }



}
